Apakhov Прогонка без зацикливания (#340)
bmstu-iu9/refal-5-lambda pull request #355
Opened 2021-05-27 17:28 UTC by Apakhov

2021-05-27 17:39 UTC, Mazdaywik commented
Пересядьте, пожалуйста, на актуальный `master`. А то Вы зачем-то некоторые коммиты задублировали по ошибке.

2021-06-01 05:59 UTC, Mazdaywik requested changes
Первая версия есть, и это замечательно. Но на данный момент у Вас реализована перестройка снизу, да и то, не полная.

Нужно реализовать перестройку сверху. Т.е. когда мы видим в графе, что срабатывает отношение остановки между текущей вершиной и одной из её родительских вершин, мы должны откатиться назад, стереть всё дерево, растущее от родительской вершины, в родительской вершине заморозить активный вызов (т.к. он привёл к зацикливанию) и продолжить построение дерева.

Цитата из #340:

> Теперь самое интересное: как построить этот граф. Строится он по следующему алгоритму:
> 
> * Выбирается очередной подлежащий оптимизации вызов функции. Функция прогоняется — получаем набор решений — сужений + замену дырки на результат шага выполнения. Если замена выполняется однозначно без сужений — решение единственное. Если прогнать нельзя — решение единственное — подстановка в дырку исходного холодного вызова.
> * Для каждого из решений строятся потомки текущей вершины. Им в историю добавляется родительская конфигурация = вся правая часть.
> * Если дочерняя конфигурация похожа на одну из своих родительских — в графе выполняется перестройка, причём перестройка сверху! В нашем случае перестройка сводится к тому, что вызов, который был активен у освистываемого предка, делается холодным. Делается попытка прогонки следующего вызова.
> 
> В последнем пункте суть. Если мы обнаружили зацикливание — потомок стал похож на предка, то значит в потомке в результате ряда развёрток появился вызов, похожий на уже вычисленный вызов в предке. Значит, этот вызов прогонять не стоило.

Суть у Вас ещё не реализована.

2021-06-01 05:59 UTC, Mazdaywik commented on src/compiler/OptTree-Drive-Expr.ref
> +}
Функция `ColdAll` точно работает?
```
<ColdAll (CallBrackets (Symbol Name 'X')) (CallBrackets (Symbol Name 'Y'))>
```

2021-06-01 05:59 UTC, Mazdaywik commented on src/compiler/OptTree-Drive-Expr.ref
> +                    = (<ComposeContractions (e.Contractions) (e.BrachContractions)> (e.BranchDrivenRight))
Очень длинная строка:
![image](https://user-images.githubusercontent.com/1309859/120272260-6ee06180-c2b5-11eb-98da-be3739e2fdb0.png)
```suggestion
                    = (
                        <ComposeContractions (e.Contractions) (e.BrachContractions)>
                        (e.BranchDrivenRight)
                      )
```
Даже здесь появляется полоса прокрутки.

2021-06-01 06:08 UTC, Mazdaywik commented
Чтобы реализовать перестройку сверху, нужно поменять формат `MakeDriveTree`:
```
<MakeDriveTree
  (s.CntNodes) (e.UsedVars) (e.WholeVars)
  t.OptInfo e.Expr (s.ThreeDepth e.History)
>
  == Tree ((s.CntNodes^) t.OptInfo^ (e.NewFunctions^)) e.DriveTree
  == Generalize s.ParentDepth
```

Если все рекурсивные вызовы в `MapAccum` вернули `Tree …`, то действуем как раньше. Если один из них вернул `Generalize s.ParentDepth`, то, если глубина совпадает с текущей глубиной, текущий активный вызов (выбранный `FindOptimizedCall`) замораживаем и делаем вторую попытку (выбираем следующий вызов при помощи `FindOptimizedCall`). Если глубина не совпадает с текущей, то возвращаем `Generalize s.ParentDepth`.

2021-06-01 07:02 UTC, Mazdaywik commented
Забыл добавить, что историю нужно смотреть снизу вверх, т.е. родителя, потом родителя родителя и т.д. Для этого или историю нужно смотреть в обратном порядке (т.е. реверсировать аргумент для `Reduce`), или формировать её в другом порядке.

2021-06-06 20:49 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +}
Поправил

2021-06-06 20:50 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +                    = (<ComposeContractions (e.Contractions) (e.BrachContractions)> (e.BranchDrivenRight))
Разбил строку

2021-06-06 20:54 UTC, Apakhov commented
Реализовал перестройку сверху, суть из #340, просмотр истории снизу вверх

2021-06-07 05:04 UTC, Mazdaywik reviewed
Попробую позапускать и тогда одобрю.

2021-06-07 05:04 UTC, Mazdaywik commented on src/compiler/OptTree-Drive-Expr.ref
> +}
```Refal5
CheckExprStopRelation {
  (e.currentExpr) e.historyExprs-B (e.historyExpr) e.historyExprs-E
    , <OptTree-CheckExprStopRelation (e.currentExpr) e.historyExpr> : True
    = <Lenw e.historyExprs-B> : s.Len e._
    = True <Inc s.Len>;

  (e.currentExpr) e.historyExprs = False 0;
}
```

2021-06-23 20:20 UTC, Mazdaywik commented
Добавьте #340 в описание последнего коммита.

В `autotests/@refal-5-lambda-diagnostics.ini` поднимите (отдельным коммитом) лимит числа шагов до
```ini
step-limit = 1000000000
```
Последнее нужно, чтобы постараться избежать конфликтов при слиянии с веткой @VladisP’а.

2021-06-23 20:42 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +}
Сделал

2021-06-23 20:42 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +                    (s.CntNodes) (e.UsedVars) (e.WholeVars) t.OptInfo <RestoreDrivenCall t.Call e.Expr>
Поправил

2021-06-23 20:42 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +    = t.OptInfo <ColdTree <MapUnBracket <FlatDriveTree e.DriveTree>>> (e.NewFunctions);
Поправил

2021-06-23 20:42 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +                ((s.CntNodes^) t.OptInfo^ (e.NewFunctionsAccum)) (e.Contractions (e.DrivenRight))
Поправил

2021-06-23 20:43 UTC, Apakhov commented on src/compiler/OptTree-Drive-Expr.ref
> +    : e.EmptyTree
Убрал

2021-06-24 05:10 UTC, Mazdaywik approved these changes
Принимаю. До защиты допускаю.

2021-06-24 05:11 UTC, merged